package oom;

import java.util.LinkedList;
import java.util.List;

public class AutoGenerateDumpFile {
	
    static class OOMObject {
        private byte[] arrs = new byte[64 * 1024];
    }

	public static void main(String[] args) {
		List<OOMObject> list = new LinkedList<>();
		while(true) {
			OOMObject oomObject = new OOMObject();
			list.add(oomObject);
		}
	}
}
